In [1]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Activation,Dense,Conv2D,MaxPool2D,Flatten,BatchNormalization,Reshape,InputLayer,GlobalAveragePooling2D,DepthwiseConv2D,Dropout,MaxPooling2D,ZeroPadding2D
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np

import itertools

In [2]:
train_path='train'
test_path='test'
valid_path='valid'

In [2]:
import os
os.chdir("Air Dataset")

In [4]:
train_batches=ImageDataGenerator(preprocessing_function=tf.keras.applications.mobilenet.preprocess_input).flow_from_directory(directory=train_path,target_size=(512,512),batch_size=32)
valid_batches=ImageDataGenerator(preprocessing_function=tf.keras.applications.mobilenet.preprocess_input).flow_from_directory(directory=valid_path,target_size=(512,512),batch_size=4)
test_batches=ImageDataGenerator(preprocessing_function=tf.keras.applications.mobilenet.preprocess_input).flow_from_directory(directory=test_path,target_size=(512,512),batch_size=4,shuffle=False)


Found 2244 images belonging to 4 classes.
Found 120 images belonging to 4 classes.
Found 120 images belonging to 4 classes.


In [5]:
mobile=tf.keras.applications.mobilenet.MobileNet()


MobileNet v1Lite without Bitshift

In [6]:
model=Sequential()
model.add(InputLayer(shape=(512, 512, 3)))

In [7]:
for layer in mobile.layers[1:43]:
     if isinstance(layer, Conv2D):
        
        #print(f'Layer {layer.name} is a Conv2D layer with {layer.filters} filters')
        newfilters=(int)(layer.filters/4)
        newlayer=Conv2D(newfilters, layer.kernel_size, strides=layer.strides,
                      padding=layer.padding, activation=layer.activation,
                      use_bias=layer.use_bias, kernel_initializer=layer.kernel_initializer,
                      bias_initializer=layer.bias_initializer)
        model.add(newlayer)
        print(f'Layer {newlayer.name} is a Conv2D layer with {newlayer.filters} filters and {newlayer.strides} strides and {newlayer.kernel_size} kernel_size')
     elif isinstance(layer, BatchNormalization) :
        model.add(BatchNormalization(axis=getattr(layer, 'axis', -1),
    momentum=getattr(layer, 'momentum', 0.99),
    epsilon=getattr(layer, 'epsilon', 1e-3),
    center=getattr(layer, 'center', True),
    scale=getattr(layer, 'scale', True),
    beta_initializer=getattr(layer, 'beta_initializer', 'zeros'),
    gamma_initializer=getattr(layer, 'gamma_initializer', 'ones'),
    moving_mean_initializer=getattr(layer, 'moving_mean_initializer', 'zeros'),
    moving_variance_initializer=getattr(layer, 'moving_variance_initializer', 'ones'),
    beta_regularizer=getattr(layer, 'beta_regularizer', None),
    gamma_regularizer=getattr(layer, 'gamma_regularizer', None),
    beta_constraint=getattr(layer, 'beta_constraint', None),
    gamma_constraint=getattr(layer, 'gamma_constraint', None)))
     elif isinstance(layer,DepthwiseConv2D):
         print(f'Layer {layer.name} is a DepthConv2D layer with  {layer.strides} strides and {layer.kernel_size} kernel size')
         model.add(DepthwiseConv2D(kernel_size=getattr(layer, 'kernel_size', (3, 3)),
    strides=getattr(layer, 'strides', (1, 1)),
    padding=getattr(layer, 'padding', 'valid'),
    depth_multiplier=getattr(layer, 'depth_multiplier', 1),
    activation=getattr(layer, 'activation', None),
    use_bias=getattr(layer, 'use_bias', True),
    bias_initializer=getattr(layer, 'bias_initializer', 'zeros'),
    depthwise_initializer=getattr(layer, 'depthwise_initializer', 'glorot_uniform')
))
     #elif(isinstance(layer,DepthwiseConv2D)):
        #     print('hellooooooooooo')
       #      print(f'Layer {layer.name} is a DepthConv2D layer with  {layer.strides} strides')
             #model.add(layer)
     elif (isinstance(layer,ZeroPadding2D)):
         print(1)

     else:
          #print(layer.name)
          model.add(layer)
     
   

Layer conv2d is a Conv2D layer with 8 filters and (2, 2) strides and (3, 3) kernel_size
Layer conv_dw_1 is a DepthConv2D layer with  (1, 1) strides and (3, 3) kernel size
Layer conv2d_1 is a Conv2D layer with 16 filters and (1, 1) strides and (1, 1) kernel_size
1
Layer conv_dw_2 is a DepthConv2D layer with  (2, 2) strides and (3, 3) kernel size
Layer conv2d_2 is a Conv2D layer with 32 filters and (1, 1) strides and (1, 1) kernel_size
Layer conv_dw_3 is a DepthConv2D layer with  (1, 1) strides and (3, 3) kernel size
Layer conv2d_3 is a Conv2D layer with 32 filters and (1, 1) strides and (1, 1) kernel_size
1
Layer conv_dw_4 is a DepthConv2D layer with  (2, 2) strides and (3, 3) kernel size
Layer conv2d_4 is a Conv2D layer with 64 filters and (1, 1) strides and (1, 1) kernel_size
Layer conv_dw_5 is a DepthConv2D layer with  (1, 1) strides and (3, 3) kernel size
Layer conv2d_5 is a Conv2D layer with 64 filters and (1, 1) strides and (1, 1) kernel_size
1
Layer conv_dw_6 is a DepthConv2D lay

In [8]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 256, 256, 8)    │           216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 256, 256, 8)    │            32 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1_relu (ReLU)               │ (None, 256, 256, 8)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ depthwise_conv2d                │ (None, 256, 256, 8)    │            72 │
│ (DepthwiseConv2D)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 256, 256, 8)    │            32 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_dw_1_relu (ReLU)           │ (None, 256, 256, 8)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 256, 256, 16)   │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 256, 256, 16)   │            64 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_pw_1_relu (ReLU)           │ (None, 256, 256, 16)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ depthwise_conv2d_1              │ (None, 127, 127, 16)   │           144 │
│ (DepthwiseConv2D)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, 127, 127, 16)   │            64 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_dw_2_relu (ReLU)           │ (None, 127, 127, 16)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 127, 127, 32)   │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_4           │ (None, 127, 127, 32)   │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_pw_2_relu (ReLU)           │ (None, 127, 127, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ depthwise_conv2d_2              │ (None, 127, 127, 32)   │           288 │
│ (DepthwiseConv2D)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_5           │ (None, 127, 127, 32)   │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_dw_3_relu (ReLU)           │ (None, 127, 127, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 127, 127, 32)   │         1,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_6           │ (None, 127, 127, 32)   │           128 │
│ (BatchNormalization)            │                        │             

 Total params: 20,400 (79.69 KB)

 Trainable params: 19,280 (75.31 KB)

 Non-trainable params: 1,120 (4.38 KB)

In [9]:
for layer in mobile.layers[73:86]:
     if isinstance(layer, Conv2D):
        
        #print(f'Layer {layer.name} is a Conv2D layer with {layer.filters} filters')
        newfilters=(int)(layer.filters/4)
        newlayer=Conv2D(newfilters, layer.kernel_size, strides=layer.strides,
                      padding=layer.padding, activation=layer.activation,
                      use_bias=layer.use_bias, kernel_initializer=layer.kernel_initializer,
                      bias_initializer=layer.bias_initializer)
        model.add(newlayer)
        print(f'Layer {newlayer.name} is a Conv2D layer with {newlayer.filters} filters and {newlayer.strides} strides and {newlayer.kernel_size} kernel_size')
     elif isinstance(layer, BatchNormalization) :
        model.add(BatchNormalization(axis=getattr(layer, 'axis', -1),
    momentum=getattr(layer, 'momentum', 0.99),
    epsilon=getattr(layer, 'epsilon', 1e-3),
    center=getattr(layer, 'center', True),
    scale=getattr(layer, 'scale', True),
    beta_initializer=getattr(layer, 'beta_initializer', 'zeros'),
    gamma_initializer=getattr(layer, 'gamma_initializer', 'ones'),
    moving_mean_initializer=getattr(layer, 'moving_mean_initializer', 'zeros'),
    moving_variance_initializer=getattr(layer, 'moving_variance_initializer', 'ones'),
    beta_regularizer=getattr(layer, 'beta_regularizer', None),
    gamma_regularizer=getattr(layer, 'gamma_regularizer', None),
    beta_constraint=getattr(layer, 'beta_constraint', None),
    gamma_constraint=getattr(layer, 'gamma_constraint', None)))
     elif isinstance(layer,DepthwiseConv2D):
         print(f'Layer {layer.name} is a DepthConv2D layer with  {layer.strides} strides and {layer.kernel_size} kernel size')

         model.add(DepthwiseConv2D(kernel_size=getattr(layer, 'kernel_size', (3, 3)),
    strides=getattr(layer, 'strides', (1, 1)),
    padding=getattr(layer, 'padding', 'valid'),
    depth_multiplier=getattr(layer, 'depth_multiplier', 1),
    activation=getattr(layer, 'activation', None),
    use_bias=getattr(layer, 'use_bias', True),
    bias_initializer=getattr(layer, 'bias_initializer', 'zeros'),
    depthwise_initializer=getattr(layer, 'depthwise_initializer', 'glorot_uniform')
))
     elif (isinstance(layer,ZeroPadding2D)):
         print(1) 
     else:
         model.add(layer)

   

1
Layer conv_dw_12 is a DepthConv2D layer with  (2, 2) strides and (3, 3) kernel size
Layer conv2d_7 is a Conv2D layer with 256 filters and (1, 1) strides and (1, 1) kernel_size
Layer conv_dw_13 is a DepthConv2D layer with  (1, 1) strides and (3, 3) kernel size
Layer conv2d_8 is a Conv2D layer with 256 filters and (1, 1) strides and (1, 1) kernel_size


In [10]:
model.add(GlobalAveragePooling2D(name='global_average_pooling2d'))
model.add(Dense(units=4,activation='softmax'))

In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 256, 256, 8)    │           216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 256, 256, 8)    │            32 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1_relu (ReLU)               │ (None, 256, 256, 8)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ depthwise_conv2d                │ (None, 256, 256, 8)    │            72 │
│ (DepthwiseConv2D)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 256, 256, 8)    │            32 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_dw_1_relu (ReLU)           │ (None, 256, 256, 8)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 256, 256, 16)   │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 256, 256, 16)   │            64 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_pw_1_relu (ReLU)           │ (None, 256, 256, 16)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ depthwise_conv2d_1              │ (None, 127, 127, 16)   │           144 │
│ (DepthwiseConv2D)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, 127, 127, 16)   │            64 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_dw_2_relu (ReLU)           │ (None, 127, 127, 16)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 127, 127, 32)   │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_4           │ (None, 127, 127, 32)   │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_pw_2_relu (ReLU)           │ (None, 127, 127, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ depthwise_conv2d_2              │ (None, 127, 127, 32)   │           288 │
│ (DepthwiseConv2D)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_5           │ (None, 127, 127, 32)   │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_dw_3_relu (ReLU)           │ (None, 127, 127, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 127, 127, 32)   │         1,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_6           │ (None, 127, 127, 32)   │           128 │
│ (BatchNormalization)            │                        │             

 Total params: 126,772 (495.20 KB)

 Trainable params: 123,860 (483.83 KB)

 Non-trainable params: 2,912 (11.38 KB)

In [5]:
model.compile(optimizer=Adam(learning_rate=0.001),loss='categorical_crossentropy',metrics=['accuracy'])



KeyboardInterrupt



In [34]:
model.fit(x=train_batches,validation_data=valid_batches,epochs=20,verbose=2)


Epoch 1/20



KeyboardInterrupt



In [13]:
model.fit(x=train_batches,validation_data=valid_batches,epochs=20,verbose=2)


Epoch 1/20


c:\Users\HP\Documents\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


71/71 - 253s - 4s/step - accuracy: 0.6872 - loss: 0.7596 - val_accuracy: 0.2500 - val_loss: 1.5832
Epoch 2/20
71/71 - 221s - 3s/step - accuracy: 0.7736 - loss: 0.5615 - val_accuracy: 0.2500 - val_loss: 2.1149
Epoch 3/20
71/71 - 223s - 3s/step - accuracy: 0.7981 - loss: 0.4750 - val_accuracy: 0.2500 - val_loss: 2.7135
Epoch 4/20
71/71 - 225s - 3s/step - accuracy: 0.8191 - loss: 0.4346 - val_accuracy: 0.2500 - val_loss: 3.4659
Epoch 5/20
71/71 - 219s - 3s/step - accuracy: 0.8258 - loss: 0.4037 - val_accuracy: 0.2500 - val_loss: 3.5441
Epoch 6/20
71/71 - 224s - 3s/step - accuracy: 0.8373 - loss: 0.3888 - val_accuracy: 0.2500 - val_loss: 3.6216
Epoch 7/20
71/71 - 220s - 3s/step - accuracy: 0.8454 - loss: 0.3495 - val_accuracy: 0.2917 - val_loss: 3.0772
Epoch 8/20
71/71 - 229s - 3s/step - accuracy: 0.8614 - loss: 0.3237 - val_accuracy: 0.6083 - val_loss: 0.9164
Epoch 9/20
71/71 - 207s - 3s/step - accuracy: 0.8739 - loss: 0.2971 - val_accuracy: 0.7417 - val_loss: 0.6955
Epoch 10/20
71/71 - 2

In [14]:
predictions=model.predict(x=test_batches,verbose=0)
rounded_pred=np.round(predictions)

In [15]:
predict=np.argmax(rounded_pred,axis=1)


In [16]:
from sklearn.metrics import f1_score,accuracy_score
test_labels=test_batches.classes

f1_micro = f1_score(test_labels, predict,average='micro')
f1_micro*100

91.66666666666666

In [18]:
model.export('mobilenetv1lite')

INFO:tensorflow:Assets written to: mobilenetv1lite\assets


INFO:tensorflow:Assets written to: mobilenetv1lite\assets


Saved artifact at 'mobilenetv1lite'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 512, 512, 3), dtype=tf.float32, name='keras_tensor_91')
Output Type:
  TensorSpec(shape=(None, 4), dtype=tf.float32, name=None)
Captures:
  2609415171024: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2609415172368: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2609415171216: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2609415172176: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2609415172560: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2609415174288: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2609415174096: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2609415175056: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2609415174864: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2609415173712: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2609415176016: TensorSpec(shape=

In [23]:
model.save_weights('weights.weights.h5')


In [25]:
model.save('mobilenetv1lite.keras')


MobileNet v1 Lite with bitshift

In [4]:
from keras.models import load_model
mobilenetv1lite=load_model('mobilenetv1lite.keras')

In [4]:
dense_weights=mobilenetv1lite.layers[-1].get_weights()[0]
dense_weights

array([[ 0.16436005, -0.15154105, -0.18714835,  0.06735396],
       [ 0.02512901, -0.07903466,  0.08077965, -0.1139873 ],
       [ 0.15105017,  0.03615137,  0.06673397, -0.05782771],
       ...,
       [ 0.09227933,  0.06480524,  0.16097234, -0.02970978],
       [ 0.07203227, -0.0595542 , -0.03374214, -0.13438588],
       [ 0.1369904 ,  0.12464586, -0.1388945 , -0.16122779]],
      dtype=float32)

In [5]:
def Quantizeweights(weights):
    #weights=weights.numpy()
    weights_absolute=tf.abs(weights)
    maxweight=tf.reduce_max(weights_absolute)
    #print(maxweight)
    scaled_weights=weights/maxweight
    #print(scaled_weights)
    lq=LQ(scaled_weights,16)
    #print(f'aloha {lq}')
    return lq
def LQ(tensor, bitwidth):
    # Create a mask for weights equal to 0
    #rounded_tensor=tf.where(tensor>0,tf.my u4xdcvp]
    # [6ath.floor(tensor),tf.math.ceil(tensor))
    rounded_weights=tensor*100
    rounded_weights=tf.where(rounded_weights>0,tf.math.floor(rounded_weights),tf.math.ceil(rounded_weights))
    epsilon = 1e-7

    # Compute weight_log using log2
    weight_log = tf.math.log(tf.math.abs(tensor)+epsilon) / tf.math.log(2.0)
    #print(weight_log)
    weight_log=tf.where(weight_log<0,tf.math.ceil(weight_log),tf.math.floor(weight_log))
    bit_pot = -2 ** bitwidth
    mask_condition = weight_log >= bit_pot
    
    # Initialize the result tensor with zeros
    result = tf.zeros_like(tensor, dtype=tf.float32)
    
    # Apply the condition where weight_log is valid
    result = tf.where(rounded_weights!=0,tf.where(mask_condition, tf.where(tensor > 0, tf.math.abs(weight_log), weight_log), result),result)
    
    return result

In [8]:
quantized_dense_weights=Quantizeweights(dense_weights)

In [9]:
quantized_dense_weights=quantized_dense_weights.numpy()
quantized_dense_weights

array([[ 0., -0., -0.,  2.],
       [ 3., -1.,  1., -1.],
       [ 0.,  3.,  2., -2.],
       ...,
       [ 1.,  2.,  0., -3.],
       [ 2., -2., -3., -1.],
       [ 1.,  1., -1., -0.]], dtype=float32)

In [10]:
qds_int=quantized_dense_weights.astype(np.int16)
qds_int

array([[ 0,  0,  0,  2],
       [ 3, -1,  1, -1],
       [ 0,  3,  2, -2],
       ...,
       [ 1,  2,  0, -3],
       [ 2, -2, -3, -1],
       [ 1,  1, -1,  0]], dtype=int16)

In [11]:
quantized_dense_weights_transp=np.transpose(qds_int)
quantized_dense_weights_transp

array([[ 0,  3,  0, ...,  1,  2,  1],
       [ 0, -1,  3, ...,  2, -2,  1],
       [ 0,  1,  2, ...,  0, -3, -1],
       [ 2, -1, -2, ..., -3, -1,  0]], dtype=int16)

In [12]:
flattened_dense=quantized_dense_weights_transp.flatten()
flattened_dense

array([ 0,  3,  0, ..., -3, -1,  0], dtype=int16)

In [23]:
hex(-3)

'-0x3'

In [17]:
np.min(flattened_dense)

-6

In [18]:
def int_to_twos_complement_hex(x, bit_width=4):
    if x >= 0:
        return format(x, 'x')  # Hexadecimal without '0x' prefix
    else:
        return format((1 << bit_width) + x, 'x')  # Two's complement hex without '0x' prefix


In [5]:
def int16_to_hex(value):
    # Check if the input is within the range of a signed 16-bit integer
    if not -32768 <= value <= 32767:
        raise ValueError("Value must be a 16-bit signed integer.")
    
    # Handle negative numbers using two's complement
    if value < 0:
        value = (1 << 16) + value
    
    # Convert to hexadecimal without '0x' and return
    return format(value, '04x')

# Example usage
print(int16_to_hex(255))   # Output: '00ff'
print(int16_to_hex(-255))  # Output: '


00ff
ff01


In [25]:
int16_to_hex(16)

'0010'

In [19]:
int_to_twos_complement_hex(16)

'10'

In [22]:
v_hex=np.vectorize(int_to_twos_complement_hex)
hex_dense=v_hex(flattened_dense)
hex_dense

array(['0', '3', '0', ..., 'd', 'f', '0'], dtype='<U1')

In [45]:
with open('dense_weights.txt', 'w') as cf:

 
 np.savetxt(cf,hex_dense,delimiter=" ",fmt="%s")


In [82]:
np.savetxt("weights.txt", qds_int, delimiter=" ", fmt="%d")

In [6]:
dense_bias=mobilenetv1lite.layers[-1].get_weights()[1]
dense_bias

array([-0.00117536,  0.00042983,  0.00199678,  0.00135183], dtype=float32)

In [6]:
def float32_to_fixed16(value, fractional_bits=8):
    # Scale by 2^fractional_bits
    scaled_value = value * (2 ** fractional_bits)
    
    # Round to the nearest integer
    fixed_value = np.round(scaled_value).astype(np.int16)
    
    # Handle overflow (for 16-bit signed integers)
    #max_val = 2**15 - 1
    #min_val = -2**15
    #fixed_value = np.clip(fixed_value, min_val, max_val)
    
    return fixed_value



In [7]:
ftf=np.vectorize(float32_to_fixed16)

#np.savetxt("weights.txt", d_bias, delimiter=",")



In [13]:
fixed_dense_bias=ftf(dense_bias)
fixed_dense_bias

array([0, 0, 1, 0], dtype=int16)

In [23]:
hex_bias=v_hex(fixed_dense_bias)

array(['0', '0', '1', '0'], dtype='<U1')

In [32]:
for i,layer in enumerate(mobilenetv1lite.layers):
    if isinstance(layer,Conv2D):
        if layer.use_bias==True:
            print(i)
            x=np.array(layer.get_weights())
            y=ftf(x)
            print(x.shape)
            print(f'weights {y}')
        
            #print(f'biases {layer.get_weights()[1]}')
    

In [7]:
for i,layer in enumerate(mobilenetv1lite.layers):
    if isinstance(layer,DepthwiseConv2D):
        if layer.use_bias==False:
            print('hayhay')
            x=np.array(layer.get_weights())
            #y=ftf(x)
            print(x.shape)
        else:
           print('hoyhoy')
           x=np.array(layer.get_weights()[0])
           y=np.array(layer.get_weights()[1])
           print(x.shape)
           print(y.shape)



        
            #print(f'weights {y}')
        

hayhay
(1, 3, 3, 8, 1)
hayhay
(1, 3, 3, 16, 1)
hayhay
(1, 3, 3, 32, 1)
hayhay
(1, 3, 3, 32, 1)
hayhay
(1, 3, 3, 64, 1)
hayhay
(1, 3, 3, 64, 1)
hayhay
(1, 3, 3, 128, 1)
hayhay
(1, 3, 3, 256, 1)


In [37]:
array_5d = np.random.rand(1, 3, 3, 3, 8)
#print(array_5d)
array_5d[:,:,:,:,0]


array([[[[0.39815469, 0.99627766, 0.41200907],
         [0.38045931, 0.84076123, 0.54737021],
         [0.88087134, 0.39220301, 0.02442792]],

        [[0.44587056, 0.26718626, 0.40811024],
         [0.43431054, 0.52770571, 0.8402363 ],
         [0.793959  , 0.45506952, 0.1813199 ]],

        [[0.43665474, 0.74319419, 0.52152409],
         [0.20976816, 0.51436807, 0.06489828],
         [0.01785718, 0.90446216, 0.30138552]]]])

In [31]:
l=array_5d[:,:,:,1,0]
l[0]

array([[0.1360771 , 0.91484703, 0.68370063],
       [0.99255511, 0.09345574, 0.90563285],
       [0.83811493, 0.54655643, 0.33519357]])

In [32]:
with open('dw2d_weights.txt', 'w') as cf:

          for i in range(0,array_5d.shape[3]):
            weights=array_5d[:,:,:,i,0]
            weights=np.array(weights)
            np.savetxt(cf,weights[0],delimiter=" ",fmt="%d")
            cf.write("\n...\n")



In [36]:
with open('conv2d_weights.txt', 'w') as cf:
        for i, layer in enumerate(mobilenetv1lite.layers):
                if isinstance(layer,Conv2D):
                     if layer.use_bias==False:
                            weights=np.array(layer.get_weights())
                            fixed_weights=ftf(weights)
                            cf.write(f'{fixed_weights.shape}\n')
                            for j in range(fixed_weights.shape[4]):
                                    kernel=fixed_weights[:,:,:,:,j]
                                    for j in range(0,fixed_weights.shape[1]):
                                           
                                           np.savetxt(cf,kernel[0][j],delimiter=" ",fmt="%d")
                                    cf.write('\n')

                     #else:
                      #      weights=np.array(layer.get_weights()[0])
                       #     fixed_weights=ftf(weights)
                        #    cf.write(f'{fixed_weights.shape}\n')
                         #   np.savetxt(cf,fixed_weights,delimiter=" ", fmt="%d")
                          #  cf.write('\n')
                           # biases=np.array(layer.get_weights()[1])
                            #fixed_biases=ftf(biases)
                            #cf.write(f'{fixed_biases.shape}\n')
                            #np.savetxt(cf,fixed_biases,delimiter=" ", fmt="%d")
                            #cf.write('\n---\n')
                            

                
                            
                     




In [35]:
with open('dw2d_weights.txt', 'w') as cf:
        for i, layer in enumerate(mobilenetv1lite.layers):
                if isinstance(layer,DepthwiseConv2D):
                     if layer.use_bias==False:
                            weights=np.array(layer.get_weights())
                            fixed_weights=ftf(weights)
                            cf.write(f'{fixed_weights.shape}\n')
                            for j in range(fixed_weights.shape[3]):
                                    kernel=fixed_weights[:,:,:,j,0]
                                    np.savetxt(cf,kernel[0],delimiter=" ",fmt="%d")
                                    cf.write('\n')
                                                                              
                            
                            cf.write('\n')

In [41]:
with open('dense_biases.txt', 'w') as cf:

 dense=mobilenetv1lite.layers[-1]
 dense_b=dense.get_weights()[1]
 fixed_point_densebiases=ftf(dense_b)
 np.savetxt(cf,[fixed_point_densebiases],delimiter=" ",fmt="%d")


In [8]:
hex_vec=np.vectorize(int16_to_hex)

In [9]:
with open('gvc.txt','w') as mf, open('gmbvc.txt','w') as gf:
   for layer in mobilenetv1lite.layers:
      if isinstance(layer,BatchNormalization):
        # Get the weights
        weights = layer.get_weights()
        gamma, beta, moving_mean, moving_variance = weights
        sqrtvar=np.sqrt(moving_variance)
        varc=1/sqrtvar
        gvc=gamma*varc
        gmbvc=(gamma*moving_mean*varc)-beta
        gmbvc=-gmbvc
       # print("varc =",varc)
        print("mean=",np.max(moving_mean))
        print("gamma=",np.max(gamma))
        print("maxgvc=",np.max(gvc))
        print("mingvc=",np.min(gvc))
        print("maxgmbvc=",np.max(gmbvc))
        print("mingmbvc=",np.min(gmbvc))
        #print("gmbvc= ",gmbvc)
        gvc=ftf(gvc,11)
        gmbvc=ftf(gmbvc,11)
        gvc=hex_vec(gvc)
        print(gvc)
        gmbvc=hex_vec(gmbvc)
       
        
       
        gf.write(f'{hex_vec(gamma.shape[0])} \n')
        np.savetxt(gf,[gmbvc],delimiter=" ",fmt="%s")
        gf.write('\n')
        mf.write(f'{hex_vec(moving_variance.shape[0])} \n')
        np.savetxt(mf,[gvc],delimiter=" ",fmt="%s")
        mf.write('\n')
        

                     
        
        
        



mean= 0.24495433
gamma= 1.0273736
maxgvc= 9.535793
mingvc= 2.0916414
maxgmbvc= 0.7149915
mingmbvc= -0.5885011
['10bc' '4c49' '202c' '1eb3' '37f4' '1353' '306c' '1aaf']
mean= 0.36294523
gamma= 1.0741372
maxgvc= 15.418801
mingvc= 1.83548
maxgmbvc= 0.72245985
mingmbvc= -0.6707628
['40be' '1aac' '41cf' '0eaf' '2ec4' '7b5a' '2c45' '146d']
mean= 0.46409115
gamma= 1.1039228
maxgvc= 3.7414162
mingvc= 1.6543442
maxgmbvc= 1.599596
mingmbvc= -1.1633953
['1518' '15b9' '1dee' '14fb' '1646' '1133' '1da2' '1761' '1115' '0ec5'
 '0e5b' '127a' '11d4' '10c2' '0d3c' '16b5']
mean= 0.10072251
gamma= 1.0549612
maxgvc= 9.469972
mingvc= 3.342732
maxgmbvc= 0.78563905
mingmbvc= -0.5959974
['30cd' '1abe' '2389' '1e81' '4bc3' '2bde' '312a' '26c5' '424d' '1f5d'
 '27ac' '293d' '4701' '247b' '46fc' '271b']
mean= 0.48349205
gamma= 1.0655665
maxgvc= 3.306471
mingvc= 1.650026
maxgmbvc= 1.0924006
mingmbvc= -1.2249463
['1115' '114c' '11c8' '1258' '1a74' '1062' '1269' '0f82' '0dab' '1489'
 '16ae' '0ebf' '102e' '0dfa' '10e2

In [47]:
with open('means.txt','w') as mf, open('gamma.txt','w') as gf:
 for layer in mobilenetv1lite.layers:
    if isinstance(layer,BatchNormalization):
        # Get the weights
        weights = layer.get_weights()
        weights=ftf(weights)
# Unpack the weights
        gamma, beta, moving_mean, moving_variance = weights
        gf.write(f'{gamma.shape} \n')
        np.savetxt(gf,[gamma],delimiter=" ",fmt="%d")
        gf.write('\n')
        mf.write(f'{moving_mean.shape} \n')
        np.savetxt(mf,[moving_mean],delimiter=" ",fmt="%d")
        mf.write('\n')
        
        



        
# Print the weights
        

In [48]:
with open('variances.txt','w') as mf, open('beta.txt','w') as gf:
 for layer in mobilenetv1lite.layers:
    if isinstance(layer,BatchNormalization):
        # Get the weights
        weights = layer.get_weights()
        weights=ftf(weights)
# Unpack the weights
        gamma, beta, moving_mean, moving_variance = weights
        gf.write(f'{beta.shape} \n')
        np.savetxt(gf,[beta],delimiter=" ",fmt="%d")
        gf.write('\n')
        mf.write(f'{moving_variance.shape} \n')
        np.savetxt(mf,[moving_variance],delimiter=" ",fmt="%d")
        mf.write('\n')

In [11]:
for layer in mobilenetv1lite.layers:
    if isinstance(layer,BatchNormalization):
        weights = layer.get_weights()
        gamma, beta, moving_mean, moving_variance = weights
        print(beta)

[-0.00773076  0.00751693  0.14207378  0.02845884  0.02265899  0.00320543
  0.02708841  0.13327822]
[ 0.03663696 -0.00315189  0.15835337 -0.00458406  0.01005088  0.01089459
  0.0394135   0.02864885]
[ 0.0696625   0.02370044  0.02450065  0.05359923  0.00185997  0.04267759
 -0.03996933 -0.04372416 -0.06870531  0.0070521   0.00633266  0.01678469
  0.06596633  0.08822378  0.05008045  0.03132116]
[ 0.01840405  0.00750033  0.07774682  0.04834275  0.00556276  0.05012243
 -0.00778291 -0.02253165  0.01866138  0.02367339 -0.03990653  0.04281659
  0.03874187 -0.01337314  0.03218598  0.03462602]
[-1.41216880e-02  3.88738401e-02 -1.35391718e-02 -3.15958750e-03
  5.88724203e-02 -4.98903822e-03  5.92829026e-02 -1.11956736e-02
  9.43732541e-03 -7.36898631e-02  2.68072449e-02  1.37576843e-02
  5.34018241e-02  7.39045739e-02  1.17806725e-01  2.84580383e-02
  1.99789517e-02  7.57969916e-02 -4.85256221e-03  1.29937157e-02
  6.78119063e-02  5.01328660e-03  6.12180829e-02  5.58023490e-02
 -4.09892760e-02 -8.

In [14]:
x=ftf(0.00750033,12)
print(x)

31


In [15]:
def to_signed_16bit_binary(decimal_number):
    if decimal_number < -32768 or decimal_number > 32767:
        raise ValueError("The number is out of range for a 16-bit signed integer")
    
    # If the number is negative, apply two's complement
    if decimal_number < 0:
        decimal_number = (1 << 16) + decimal_number  # 2^16 + decimal_number
    
    # Convert to binary and pad to 16 bits
    binary_representation = format(decimal_number, '016b')
    
    return binary_representation

# Test the function
print(to_signed_16bit_binary(300))    # Output: '0000000100101100'
print(to_signed_16bit_binary(-300))   # Output: '1111111011010100'
print(to_signed_16bit_binary(32767))  # Output: '0111111111111111'
print(to_signed_16bit_binary(-32768)) # Output: '1000000000000000'


0000000100101100
1111111011010100
0111111111111111
1000000000000000


In [18]:
to_signed_16bit_binary(2)

'0000000000000010'

In [45]:
for layer in mobilenetv1lite.layers:
    if isinstance(layer,BatchNormalization):
        # Get the weights
        weights = layer.get_weights()
        weights=ftf(weights)
# Unpack the weights
        gamma, beta, moving_mean, moving_variance = weights
        print(gamma)
        print(beta.shape)
        print(moving_mean)
        print(moving_variance)

[244 249 231 263 253 259 257 220]
(8,)
[-77 -19 -32 -42   9  63  24 -35]
[53  3 13 18  5 45  7 17]
[244 243 275 246 248 253 254 260]
(8,)
[-13 -51   7  93 -22  10  12 -70]
[ 4 21  4 70  7  1  8 41]
[241 260 263 273 253 258 245 239 236 270 244 283 253 252 253 239]
(16,)
[-149   28   -2  119  -21   48  -14  -28  113   21   27   37  -54    0
 -116    8]
[33 36 19 42 32 56 17 26 48 84 72 58 50 56 91 28]
[245 242 267 263 258 253 246 248 252 254 241 269 260 270 264 254]
(16,)
[ 26 -36 -20 -32   3  13 -33  -4  11 -49   0 -24 -16   7 -11  22]
[ 6 20 14 19  3  8  6 10  4 16  9 11  3 14  3 11]
[262 273 245 235 269 219 249 250 233 254 267 250 229 261 256 242 253 256
 233 262 252 248 242 264 265 256 258 251 235 253 254 245]
(32,)
[  43   95  -13  124   32   19   58   78  -94  -42   -2  -93  -10  -64
  -17  -11   -4  -63   26   41 -120  -99   33   38  -97   89  -91  -46
  115  -90   42   -6]
[59 62 47 41 26 45 46 65 72 38 35 72 50 87 57 43 55 64 57 76 52 81 38 44
 49 52 84 67 27 92 64 53]
[258 248 

In [7]:
mobilenetv1liteQuantized=Sequential()

In [8]:
for layer in mobilenetv1lite.layers[:-1]:
    mobilenetv1liteQuantized.add(layer)

In [9]:
mobilenetv1liteQuantized.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 256, 256, 8)    │           216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 256, 256, 8)    │            32 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1_relu (ReLU)               │ (None, 256, 256, 8)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ depthwise_conv2d                │ (None, 256, 256, 8)    │            72 │
│ (DepthwiseConv2D)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 256, 256, 8)    │            32 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_dw_1_relu (ReLU)           │ (None, 256, 256, 8)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 256, 256, 16)   │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 256, 256, 16)   │            64 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_pw_1_relu (ReLU)           │ (None, 256, 256, 16)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ depthwise_conv2d_1              │ (None, 127, 127, 16)   │           144 │
│ (DepthwiseConv2D)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, 127, 127, 16)   │            64 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_dw_2_relu (ReLU)           │ (None, 127, 127, 16)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 127, 127, 32)   │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_4           │ (None, 127, 127, 32)   │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_pw_2_relu (ReLU)           │ (None, 127, 127, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ depthwise_conv2d_2              │ (None, 127, 127, 32)   │           288 │
│ (DepthwiseConv2D)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_5           │ (None, 127, 127, 32)   │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_dw_3_relu (ReLU)           │ (None, 127, 127, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 127, 127, 32)   │         1,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_6           │ (None, 127, 127, 32)   │           128 │
│ (BatchNormalization)            │                        │             

 Total params: 125,744 (491.19 KB)

 Trainable params: 122,832 (479.81 KB)

 Non-trainable params: 2,912 (11.38 KB)

In [10]:
os.chdir('..')
os.getcwd()

'c:\\Users\\HP\\Documents\\GitHub\\CNN-ON-FPGA-MSc.-\\Training Model(Python)'

In [11]:
import ml_dtypes

from keras.src import activations
from keras.src import constraints
from keras.src import dtype_policies
from keras.src import initializers
from keras.src import ops
from keras.src import quantizers
from keras.src import regularizers
from keras.src.api_export import keras_export
from keras.src.layers.input_spec import InputSpec
from keras.src.layers.layer import Layer
import numpy 
#@tf.custom_gradient
def bitshift(weight,shift):
  res=0
  if shift<0:
       y=tf.math.abs(shift)
       res= tf.bitwise.right_shift(weight,y)
  else:
       res= tf.bitwise.left_shift(weight,shift)
def MatrixBitShift(A,B):
    #def grd(dy):
     #   G=ops.matmult(dy,ops.transpose(D))
      #  return G

    A=tf.cast(A,tf.int32)
    B=tf.cast(B,tf.int32)
    columns2=tf.shape(B)[1]
    rows2=tf.shape(B)[0]
    rows1=tf.shape(A)[0]
    C=tf.zeros(shape=(rows1,columns2),dtype=tf.int32)
    for i in range(0,rows1):
      for j in range(0,rows2):
            for  k in range(0,columns2):
                original=C[i][k]
                a=A[i][j]
                b=B[j][k]
                x=bitshift(a,b)
                #print(x)
                update=original+x
                
                index=tf.constant([[i,k]])
                #u=tf.constant([update],dtype=tf.int32)
                C=tf.tensor_scatter_nd_update(C,index,[update])
    
    return C

def Quantizeweights(weights):
    #weights=weights.numpy()
    weights_absolute=tf.abs(weights)
    maxweight=tf.reduce_max(weights_absolute)
    #print(maxweight)
    scaled_weights=weights/maxweight
    #print(scaled_weights)
    lq=LQ(scaled_weights,4)
    #print(f'aloha {lq}')
    return lq
#@tf.custom_gradient

 # def grad(dy):
  #     dw=2**shift*dy
   #    ds=2**shift*weight*tf.math.log(2)*dy
    #   return dw,ds
#return res
    
    #pot_vect=numpy.vectorize(powertwo)
    #final_weights=pot_vect(lq,maxweight)
    #print(final_weights)



def check_integer_zero_and_first_two_decimals_zero(number):
    # Check if the integer part is zero
    if int(number) != 0:
        return False
    
    # Convert the number to a string
    num_str = str(number)
    
    # Find the decimal point
    decimal_point_index = num_str.find('.')
    
    # Check if there is a decimal point and if the length after the decimal point is at least 2
    if decimal_point_index != -1 and len(num_str) > decimal_point_index + 2:
        # Get the first two decimal places
        first_two_decimals = num_str[decimal_point_index + 1:decimal_point_index + 3]
        # Check if the first two decimal places are "00"
        return first_two_decimals == "00"
    
    # If there are no decimal places or less than two decimal places, return False
    return False
def clip(weight,bitwidth):
    
    weight_log=numpy.round(numpy.log2(numpy.absolute(weight)))
    bit_pot=-2**bitwidth
    if weight_log<bit_pot:
        return 0
    elif weight_log>=0:
        return -1
    else:
        return weight_log
def LQ(tensor, bitwidth):
    # Create a mask for weights equal to 0
    #rounded_tensor=tf.where(tensor>0,tf.my u4xdcvp]
    # [6ath.floor(tensor),tf.math.ceil(tensor))
    rounded_weights=tensor*100
    rounded_weights=tf.where(rounded_weights>0,tf.math.floor(rounded_weights),tf.math.ceil(rounded_weights))
    epsilon = 1e-7

    # Compute weight_log using log2
    weight_log = tf.math.log(tf.math.abs(tensor)+epsilon) / tf.math.log(2.0)
    #print(weight_log)
    weight_log=tf.where(weight_log<0,tf.math.ceil(weight_log),tf.math.floor(weight_log))
    bit_pot = -2 ** bitwidth
    mask_condition = weight_log >= bit_pot
    
    # Initialize the result tensor with zeros
    result = tf.zeros_like(tensor, dtype=tf.float32)
    
    # Apply the condition where weight_log is valid
    result = tf.where(rounded_weights!=0,tf.where(mask_condition, tf.where(tensor > 0, tf.math.abs(weight_log), weight_log), result),result)
    
    return result

def powertwo(weight,sf):
    pot_weight=(2**weight)*sf
    return pot_weight
    

class QDense(Layer):
    """Just your regular densely-connected NN layer with Quantized weights and bit shifting.

    `Dense` implements the operation:
    `output = activation(dot(input, kernel) + bias)`
    where `activation` is the element-wise activation function
    passed as the `activation` argument, `kernel` is a weights matrix
    created by the layer, and `bias` is a bias vector created by the layer
    (only applicable if `use_bias` is `True`).

    Note: If the input to the layer has a rank greater than 2, `Dense`
    computes the dot product between the `inputs` and the `kernel` along the
    last axis of the `inputs` and axis 0 of the `kernel` (using `tf.tensordot`).
    For example, if input has dimensions `(batch_size, d0, d1)`, then we create
    a `kernel` with shape `(d1, units)`, and the `kernel` operates along axis 2
    of the `input`, on every sub-tensor of shape `(1, 1, d1)` (there are
    `batch_size * d0` such sub-tensors). The output in this case will have
    shape `(batch_size, d0, units)`.

    Args:
        units: Positive integer, dimensionality of the output space.
        activation: Activation function to use.
            If you don't specify anything, no activation is applied
            (ie. "linear" activation: `a(x) = x`).
        use_bias: Boolean, whether the layer uses a bias vector.
        kernel_initializer: Initializer for the `kernel` weights matrix.
        bias_initializer: Initializer for the bias vector.
        kernel_regularizer: Regularizer function applied to
            the `kernel` weights matrix.
        bias_regularizer: Regularizer function applied to the bias vector.
        activity_regularizer: Regularizer function applied to
            the output of the layer (its "activation").
        kernel_constraint: Constraint function applied to
            the `kernel` weights matrix.
        bias_constraint: Constraint function applied to the bias vector.
        lora_rank: Optional integer. If set, the layer's forward pass
            will implement LoRA (Low-Rank Adaptation)
            with the provided rank. LoRA sets the layer's kernel
            to non-trainable and replaces it with a delta over the
            original kernel, obtained via multiplying two lower-rank
            trainable matrices. This can be useful to reduce the
            computation cost of fine-tuning large dense layers.
            You can also enable LoRA on an existing
            `Dense` layer by calling `layer.enable_lora(rank)`.

    Input shape:
        N-D tensor with shape: `(batch_size, ..., input_dim)`.
        The most common situation would be
        a 2D input with shape `(batch_size, input_dim)`.

    Output shape:
        N-D tensor with shape: `(batch_size, ..., units)`.
        For instance, for a 2D input with shape `(batch_size, input_dim)`,
        the output would have shape `(batch_size, units)`.
    """

    def __init__(
        self,
        units,
        activation=None,
        use_bias=True,
        kernel_initializer="glorot_uniform",
        bias_initializer="zeros",
        kernel_regularizer=None,
        bias_regularizer=None,
        activity_regularizer=None,
        kernel_constraint=None,
        bias_constraint=None,
        lora_rank=None,
        **kwargs,
    ):
        super().__init__(activity_regularizer=activity_regularizer, **kwargs)
        self.units = units
        self.activation = activations.get(activation)
        self.use_bias = use_bias
        self.kernel_initializer = initializers.get(kernel_initializer)
        self.bias_initializer = initializers.get(bias_initializer)
        self.kernel_regularizer = regularizers.get(kernel_regularizer)
        self.bias_regularizer = regularizers.get(bias_regularizer)
        self.kernel_constraint = constraints.get(kernel_constraint)
        self.bias_constraint = constraints.get(bias_constraint)
        self.lora_rank = lora_rank
        self.lora_enabled = False
        self.input_spec = InputSpec(min_ndim=2)
        self.supports_masking = True

    def build(self, input_shape):
        input_dim = input_shape[-1]
        # We use `self._dtype_policy` to check to avoid issues in torch dynamo
        is_quantized = isinstance(
            self._dtype_policy, dtype_policies.QuantizedDTypePolicy
        )
        if is_quantized:
            self.quantized_build(
                input_shape, mode=self.dtype_policy.quantization_mode
            )
        if not is_quantized or self.dtype_policy.quantization_mode != "int8":
            # If the layer is quantized to int8, `self._kernel` will be added
            # in `self._int8_build`. Therefore, we skip it here.
            self._kernel = self.add_weight(
                name="kernel",
                shape=(input_dim, self.units),
                initializer=self.kernel_initializer,
                regularizer=self.kernel_regularizer,
                constraint=self.kernel_constraint,
            )
        if self.use_bias:
            self.bias = self.add_weight(
                name="bias",
                shape=(self.units,),
                initializer=self.bias_initializer,
                regularizer=self.bias_regularizer,
                constraint=self.bias_constraint,
            )
        else:
            self.bias = None
        self.input_spec = InputSpec(min_ndim=2, axes={-1: input_dim})
        self.built = True
        if self.lora_rank:
            self.enable_lora(self.lora_rank)

    @property
    def kernel(self):
        if not self.built:
            raise AttributeError(
                "You must build the layer before accessing `kernel`."
            )
        if self.lora_enabled:
            return self._kernel + ops.matmul(
                self.lora_kernel_a, self.lora_kernel_b
            )
        return self._kernel

    def call(self, inputs):
        
        quantized_weights=Quantizeweights(self.kernel)
        #x = ops.matmul(inputs, self.kernel)
        x=MatrixBitShift(inputs,quantized_weights,self.kernel)
        if self.bias is not None:
            x = ops.add(x, self.bias)
        if self.activation is not None:
            x = self.activation(x)
        return x

    def compute_output_shape(self, input_shape):
        output_shape = list(input_shape)
        output_shape[-1] = self.units
        return tuple(output_shape)

    def enable_lora(
        self, rank, a_initializer="he_uniform", b_initializer="zeros"
    ):
        if self.kernel_constraint:
            raise ValueError(
                "Lora is incompatible with kernel constraints. "
                "In order to enable lora on this layer, remove the "
                "`kernel_constraint` argument."
            )
        if not self.built:
            raise ValueError(
                "Cannot enable lora on a layer that isn't yet built."
            )
        if self.lora_enabled:
            raise ValueError(
                "lora is already enabled. "
                "This can only be done once per layer."
            )
        self._tracker.unlock()
        self.lora_kernel_a = self.add_weight(
            name="lora_kernel_a",
            shape=(self.kernel.shape[0], rank),
            initializer=initializers.get(a_initializer),
            regularizer=self.kernel_regularizer,
        )
        self.lora_kernel_b = self.add_weight(
            name="lora_kernel_b",
            shape=(rank, self.kernel.shape[1]),
            initializer=initializers.get(b_initializer),
            regularizer=self.kernel_regularizer,
        )
        self._kernel.trainable = False
        self._tracker.lock()
        self.lora_enabled = True
        self.lora_rank = rank

    def save_own_variables(self, store):
        # Do nothing if the layer isn't yet built
        if not self.built:
            return
        # The keys of the `store` will be saved as determined because the
        # default ordering will change after quantization
        kernel_value, kernel_scale = self._get_kernel_with_merged_lora()
        target_variables = [kernel_value]
        if self.use_bias:
            target_variables.append(self.bias)
        if isinstance(self.dtype_policy, dtype_policies.QuantizedDTypePolicy):
            mode = self.dtype_policy.quantization_mode
            if mode == "int8":
                target_variables.append(kernel_scale)
            elif mode == "float8":
                target_variables.append(self.inputs_scale)
                target_variables.append(self.inputs_amax_history)
                target_variables.append(self.kernel_scale)
                target_variables.append(self.kernel_amax_history)
                target_variables.append(self.outputs_grad_scale)
                target_variables.append(self.outputs_grad_amax_history)
            else:
                raise NotImplementedError(
                    self.QUANTIZATION_MODE_ERROR_TEMPLATE.format(mode)
                )
        for i, variable in enumerate(target_variables):
            store[str(i)] = variable

    def load_own_variables(self, store):
        if not self.lora_enabled:
            self._check_load_own_variables(store)
        # Do nothing if the layer isn't yet built
        if not self.built:
            return
        # The keys of the `store` will be saved as determined because the
        # default ordering will change after quantization
        target_variables = [self._kernel]
        if self.use_bias:
            target_variables.append(self.bias)
        if isinstance(self.dtype_policy, dtype_policies.QuantizedDTypePolicy):
            mode = self.dtype_policy.quantization_mode
            if mode == "int8":
                target_variables.append(self.kernel_scale)
            elif mode == "float8":
                target_variables.append(self.inputs_scale)
                target_variables.append(self.inputs_amax_history)
                target_variables.append(self.kernel_scale)
                target_variables.append(self.kernel_amax_history)
                target_variables.append(self.outputs_grad_scale)
                target_variables.append(self.outputs_grad_amax_history)
            else:
                raise NotImplementedError(
                    self.QUANTIZATION_MODE_ERROR_TEMPLATE.format(mode)
                )
        for i, variable in enumerate(target_variables):
            variable.assign(store[str(i)])
        if self.lora_enabled:
            self.lora_kernel_a.assign(ops.zeros(self.lora_kernel_a.shape))
            self.lora_kernel_b.assign(ops.zeros(self.lora_kernel_b.shape))

    def get_config(self):
        base_config = super().get_config()
        config = {
            "units": self.units,
            "activation": activations.serialize(self.activation),
            "use_bias": self.use_bias,
            "kernel_initializer": initializers.serialize(
                self.kernel_initializer
            ),
            "bias_initializer": initializers.serialize(self.bias_initializer),
            "kernel_regularizer": regularizers.serialize(
                self.kernel_regularizer
            ),
            "bias_regularizer": regularizers.serialize(self.bias_regularizer),
            "kernel_constraint": constraints.serialize(self.kernel_constraint),
            "bias_constraint": constraints.serialize(self.bias_constraint),
        }
        if self.lora_rank:
            config["lora_rank"] = self.lora_rank
        return {**base_config, **config}

    def _check_load_own_variables(self, store):
        all_vars = self._trainable_variables + self._non_trainable_variables
        if len(store.keys()) != len(all_vars):
            if len(all_vars) == 0 and not self.built:
                raise ValueError(
                    f"Layer '{self.name}' was never built "
                    "and thus it doesn't have any variables. "
                    f"However the weights file lists {len(store.keys())} "
                    "variables for this layer.\n"
                    "In most cases, this error indicates that either:\n\n"
                    "1. The layer is owned by a parent layer that "
                    "implements a `build()` method, but calling the "
                    "parent's `build()` method did NOT create the state of "
                    f"the child layer '{self.name}'. A `build()` method "
                    "must create ALL state for the layer, including "
                    "the state of any children layers.\n\n"
                    "2. You need to implement "
                    "the `def build_from_config(self, config)` method "
                    f"on layer '{self.name}', to specify how to rebuild "
                    "it during loading. "
                    "In this case, you might also want to implement the "
                    "method that generates the build config at saving time, "
                    "`def get_build_config(self)`. "
                    "The method `build_from_config()` is meant "
                    "to create the state "
                    "of the layer (i.e. its variables) upon deserialization.",
                )
            raise ValueError(
                f"Layer '{self.name}' expected {len(all_vars)} variables, "
                "but received "
                f"{len(store.keys())} variables during loading. "
                f"Expected: {[v.name for v in all_vars]}"
            )

    """Quantization-related (int8 and float8) methods"""

    QUANTIZATION_MODE_ERROR_TEMPLATE = (
        f"Invalid quantization mode. Expected one of "
        f"{dtype_policies.QUANTIZATION_MODES}. "
        "Received: quantization_mode={mode}"
    )

    def quantized_build(self, input_shape, mode):
        if mode == "int8":
            input_dim = input_shape[-1]
            kernel_shape = (input_dim, self.units)
            self._int8_build(kernel_shape)
        elif mode == "float8":
            self._float8_build()
        else:
            raise NotImplementedError(
                self.QUANTIZATION_MODE_ERROR_TEMPLATE.format(mode)
            )

    def _int8_build(
        self,
        kernel_shape,
        kernel_initializer="zeros",
        kernel_scale_initializer="ones",
    ):
        self.inputs_quantizer = quantizers.AbsMaxQuantizer(axis=-1)
        self._kernel = self.add_weight(
            name="kernel",
            shape=kernel_shape,
            initializer=kernel_initializer,
            dtype="int8",
            trainable=False,
        )
        self.kernel_scale = self.add_weight(
            name="kernel_scale",
            shape=(self.units,),
            initializer=kernel_scale_initializer,
            trainable=False,
        )
        self._is_quantized = True

    def _float8_build(self):
        if not isinstance(
            self.dtype_policy, dtype_policies.QuantizedFloat8DTypePolicy
        ):
            raise TypeError(
                "`self.dtype_policy` must be the type of "
                f"QuantizedFloat8DTypePolicy. Received {self.dtype_policy}"
            )
        amax_history_length = self.dtype_policy.amax_history_length
        # We set `trainable=True` because we will use the gradients to overwrite
        # these variables
        scale_kwargs = {
            "shape": (),
            "initializer": "ones",
            "dtype": "float32",  # Always be float32
            "trainable": True,
            "autocast": False,
        }
        amax_history_kwargs = {
            "shape": (amax_history_length,),
            "initializer": "zeros",
            "dtype": "float32",  # Always be float32
            "trainable": True,
            "autocast": False,
        }
        self.inputs_scale = self.add_weight(name="inputs_scale", **scale_kwargs)
        self.inputs_amax_history = self.add_weight(
            name="inputs_amax_history", **amax_history_kwargs
        )
        self.kernel_scale = self.add_weight(name="kernel_scale", **scale_kwargs)
        self.kernel_amax_history = self.add_weight(
            name="kernel_amax_history", **amax_history_kwargs
        )
        self.outputs_grad_scale = self.add_weight(
            name="outputs_grad_scale", **scale_kwargs
        )
        self.outputs_grad_amax_history = self.add_weight(
            name="outputs_grad_amax_history", **amax_history_kwargs
        )
        # We need to set `overwrite_with_gradient=True` to instruct the
        # optimizer to directly overwrite these variables with their computed
        # gradients during training
        self.inputs_scale.overwrite_with_gradient = True
        self.inputs_amax_history.overwrite_with_gradient = True
        self.kernel_scale.overwrite_with_gradient = True
        self.kernel_amax_history.overwrite_with_gradient = True
        self.outputs_grad_scale.overwrite_with_gradient = True
        self.outputs_grad_amax_history.overwrite_with_gradient = True
        self._is_quantized = True

    def quantized_call(self, inputs):
        if self.dtype_policy.quantization_mode == "int8":
            return self._int8_call(inputs)
        elif self.dtype_policy.quantization_mode == "float8":
            return self._float8_call(inputs)
        else:
            mode = self.dtype_policy.quantization_mode
            raise NotImplementedError(
                self.QUANTIZATION_MODE_ERROR_TEMPLATE.format(mode)
            )

    def _int8_call(self, inputs):
        @ops.custom_gradient
        def matmul_with_inputs_gradient(inputs, kernel, kernel_scale):
            def grad_fn(*args, upstream=None):
                if upstream is None:
                    (upstream,) = args
                float_kernel = ops.divide(
                    ops.cast(kernel, dtype=self.compute_dtype),
                    kernel_scale,
                )
                inputs_grad = ops.matmul(upstream, ops.transpose(float_kernel))
                return (inputs_grad, None, None)

            inputs, inputs_scale = self.inputs_quantizer(inputs)
            x = ops.matmul(inputs, kernel)
            # De-scale outputs
            x = ops.cast(x, self.compute_dtype)
            x = ops.divide(x, ops.multiply(inputs_scale, kernel_scale))
            return x, grad_fn

        x = matmul_with_inputs_gradient(
            inputs,
            ops.convert_to_tensor(self._kernel),
            ops.convert_to_tensor(self.kernel_scale),
        )
        if self.lora_enabled:
            lora_x = ops.matmul(inputs, self.lora_kernel_a)
            lora_x = ops.matmul(lora_x, self.lora_kernel_b)
            x = ops.add(x, lora_x)
        if self.bias is not None:
            x = ops.add(x, self.bias)
        if self.activation is not None:
            x = self.activation(x)
        return x

    def _float8_call(self, inputs):
        if self.lora_enabled:
            raise NotImplementedError(
                "Currently, `_float8_call` doesn't support LoRA"
            )

        @ops.custom_gradient
        def quantized_dequantize_inputs(inputs, scale, amax_history):
            new_scale = quantizers.compute_float8_scale(
                ops.max(amax_history, axis=0),
                scale,
                ops.cast(
                    float(ml_dtypes.finfo("float8_e4m3fn").max), "float32"
                ),
            )
            qdq_inputs = quantizers.quantize_and_dequantize(
                inputs, scale, "float8_e4m3fn", self.compute_dtype
            )
            new_amax_history = quantizers.compute_float8_amax_history(
                inputs, amax_history
            )

            def grad(*args, upstream=None, variables=None):
                if upstream is None:
                    (upstream,) = args
                return upstream, new_scale, new_amax_history

            return qdq_inputs, grad

        @ops.custom_gradient
        def quantized_dequantize_outputs(outputs, scale, amax_history):
            """Quantize-dequantize the output gradient but not the output."""

            def grad(*args, upstream=None, variables=None):
                if upstream is None:
                    (upstream,) = args
                new_scale = quantizers.compute_float8_scale(
                    ops.max(amax_history, axis=0),
                    scale,
                    ops.cast(
                        float(ml_dtypes.finfo("float8_e5m2").max), "float32"
                    ),
                )
                qdq_upstream = quantizers.quantize_and_dequantize(
                    upstream, scale, "float8_e5m2", self.compute_dtype
                )
                new_amax_history = quantizers.compute_float8_amax_history(
                    upstream, amax_history
                )
                return qdq_upstream, new_scale, new_amax_history

            return outputs, grad

        x = ops.matmul(
            quantized_dequantize_inputs(
                inputs,
                ops.convert_to_tensor(self.inputs_scale),
                ops.convert_to_tensor(self.inputs_amax_history),
            ),
            quantized_dequantize_inputs(
                ops.convert_to_tensor(self._kernel),
                ops.convert_to_tensor(self.kernel_scale),
                ops.convert_to_tensor(self.kernel_amax_history),
            ),
        )
        # `quantized_dequantize_outputs` is placed immediately after
        # `ops.matmul` for the sake of pattern matching in gemm_rewrite. That
        # way, the qdq will be adjacent to the corresponding matmul_bprop in the
        # bprop.
        x = quantized_dequantize_outputs(
            x,
            ops.convert_to_tensor(self.outputs_grad_scale),
            ops.convert_to_tensor(self.outputs_grad_amax_history),
        )
        if self.bias is not None:
            # Under non-mixed precision cases, F32 bias has to be converted to
            # BF16 first to get the biasAdd fusion support. ref. PR
            # https://github.com/tensorflow/tensorflow/pull/60306
            bias = self.bias
            if self.dtype_policy.compute_dtype == "float32":
                bias_bf16 = ops.cast(bias, "bfloat16")
                bias = ops.cast(bias_bf16, bias.dtype)
            x = ops.add(x, bias)
        if self.activation is not None:
            x = self.activation(x)
        return x

    def quantize(self, mode):
        import gc

        # Prevent quantization of the subclasses
        if type(self) is not Dense:
            raise NotImplementedError(
                f"Layer {self.__class__.__name__} does not have a `quantize()` "
                "method implemented."
            )
        self._check_quantize_args(mode, self.compute_dtype)

        # Set new dtype policy
        if not isinstance(
            self.dtype_policy, dtype_policies.QuantizedDTypePolicy
        ):
            quantized_dtype = f"{mode}_from_{self.dtype_policy.name}"
            # We set the internal `self._dtype_policy` instead of using the
            # setter to avoid double `quantize` call
            self._dtype_policy = dtype_policies.get(quantized_dtype)

        self._tracker.unlock()
        if mode == "int8":
            # Quantize `self._kernel` to int8 and compute corresponding scale
            kernel_value, kernel_scale = quantizers.abs_max_quantize(
                self._kernel, axis=0
            )
            kernel_scale = ops.squeeze(kernel_scale, axis=0)
            self._untrack_variable(self._kernel)
            kernel_shape = self._kernel.shape
            del self._kernel
            # Utilize a lambda expression as an initializer to prevent adding a
            # large constant to the computation graph.
            self._int8_build(
                kernel_shape,
                lambda shape, dtype: kernel_value,
                lambda shape, dtype: kernel_scale,
            )
        elif mode == "float8":
            self._float8_build()
        else:
            raise NotImplementedError(
                self.QUANTIZATION_MODE_ERROR_TEMPLATE.format(mode)
            )
        self._tracker.lock()

        # Release memory manually because sometimes the backend doesn't
        gc.collect()

    def _get_kernel_with_merged_lora(self):
        if isinstance(self.dtype_policy, dtype_policies.QuantizedDTypePolicy):
            kernel_value = self._kernel
            kernel_scale = self.kernel_scale
            if self.lora_enabled:
                # Dequantize & quantize to merge lora weights into int8 kernel
                # Note that this is a lossy compression
                kernel_value = ops.divide(kernel_value, kernel_scale)
                kernel_value = ops.add(
                    kernel_value,
                    ops.matmul(self.lora_kernel_a, self.lora_kernel_b),
                )
                kernel_value, kernel_scale = quantizers.abs_max_quantize(
                    kernel_value, axis=0
                )
                kernel_scale = ops.squeeze(kernel_scale, axis=0)
            return kernel_value, kernel_scale
        return self.kernel, None
    

IndentationError: unindent does not match any outer indentation level (<string>, line 65)

In [12]:
mobilenetv1liteQuantized.add(QDense(units=4,activation='softmax'))


In [13]:
mobilenetv1liteQuantized.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 256, 256, 8)    │           216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 256, 256, 8)    │            32 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1_relu (ReLU)               │ (None, 256, 256, 8)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ depthwise_conv2d                │ (None, 256, 256, 8)    │            72 │
│ (DepthwiseConv2D)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 256, 256, 8)    │            32 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_dw_1_relu (ReLU)           │ (None, 256, 256, 8)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 256, 256, 16)   │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 256, 256, 16)   │            64 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_pw_1_relu (ReLU)           │ (None, 256, 256, 16)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ depthwise_conv2d_1              │ (None, 127, 127, 16)   │           144 │
│ (DepthwiseConv2D)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, 127, 127, 16)   │            64 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_dw_2_relu (ReLU)           │ (None, 127, 127, 16)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 127, 127, 32)   │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_4           │ (None, 127, 127, 32)   │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_pw_2_relu (ReLU)           │ (None, 127, 127, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ depthwise_conv2d_2              │ (None, 127, 127, 32)   │           288 │
│ (DepthwiseConv2D)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_5           │ (None, 127, 127, 32)   │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_dw_3_relu (ReLU)           │ (None, 127, 127, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 127, 127, 32)   │         1,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_6           │ (None, 127, 127, 32)   │           128 │
│ (BatchNormalization)            │                        │             

 Total params: 125,744 (491.19 KB)

 Trainable params: 122,832 (479.81 KB)

 Non-trainable params: 2,912 (11.38 KB)

In [67]:
for layer in mobilenetv1liteQuantized.layers[:-1]:
   layer.trainable=True

In [14]:
mobilenetv1liteQuantized.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 256, 256, 8)    │           216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 256, 256, 8)    │            32 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1_relu (ReLU)               │ (None, 256, 256, 8)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ depthwise_conv2d                │ (None, 256, 256, 8)    │            72 │
│ (DepthwiseConv2D)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 256, 256, 8)    │            32 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_dw_1_relu (ReLU)           │ (None, 256, 256, 8)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 256, 256, 16)   │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 256, 256, 16)   │            64 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_pw_1_relu (ReLU)           │ (None, 256, 256, 16)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ depthwise_conv2d_1              │ (None, 127, 127, 16)   │           144 │
│ (DepthwiseConv2D)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, 127, 127, 16)   │            64 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_dw_2_relu (ReLU)           │ (None, 127, 127, 16)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 127, 127, 32)   │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_4           │ (None, 127, 127, 32)   │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_pw_2_relu (ReLU)           │ (None, 127, 127, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ depthwise_conv2d_2              │ (None, 127, 127, 32)   │           288 │
│ (DepthwiseConv2D)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_5           │ (None, 127, 127, 32)   │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_dw_3_relu (ReLU)           │ (None, 127, 127, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 127, 127, 32)   │         1,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_6           │ (None, 127, 127, 32)   │           128 │
│ (BatchNormalization)            │                        │             

 Total params: 125,744 (491.19 KB)

 Trainable params: 122,832 (479.81 KB)

 Non-trainable params: 2,912 (11.38 KB)

In [15]:
mobilenetv1liteQuantized.compile(optimizer=Adam(learning_rate=0.001),loss='categorical_crossentropy',metrics=['accuracy'])

In [16]:
os.chdir("Air Dataset")

In [20]:
import tensorflow as tf

# Enable eager execution
tf.config.run_functions_eagerly(False)


In [22]:
def bitshift2(weight,shift):
    if shift<0:
       y=tf.math.abs(shift)
       return tf.bitwise.right_shift(weight,shift)
    else:
       return tf.bitwise.left_shift(weight,shift)

In [23]:
def MatrixBitShift(A,B):
    A=tf.cast(A,tf.int32)
    B=tf.cast(B,tf.int32)
    columns2=tf.shape(B)[1]
    rows2=tf.shape(B)[0]
    rows1=tf.shape(A)[0]
    print(rows1)
    C=tf.zeros(shape=(rows1,columns2),dtype=tf.int32)
    for i in range(0,rows1):
      for j in range(0,rows2):
            for  k in range(0,columns2):
                original=C[i][k]
                a=A[i][j]
                b=B[j][k]
                x=bitshift2(a,b)
                #print(x)
                update=original+x
                
                index=tf.constant([[i,k]])
                #u=tf.constant([update],dtype=tf.int32)
                C=tf.tensor_scatter_nd_update(C,index,[update])
    return C

In [24]:
tensor = tf.constant([[1, 1, 2, 3],[1,1,2,3]])
tens2=tf.constant([[1,1,1],[1,1,1],[1,1,1],[1,1,1]])
C=MatrixBitShift(tensor,tens2)
print(C)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[14 14 14]
 [14 14 14]], shape=(2, 3), dtype=int32)
